:bug: 힙 메모리 초과 예외 해결 (#186)
ahachulTeam/ahachul_backend2 pull request #187
Opened 2023-10-28 02:15 UTC by semi-cloud

## 📚 개요
+ #186 

## ✏️ 작업 내용
+ DB 바뀐 후 데이터가 다 날라갔고, Lostt112 모든 데이터가 들어있는 파일을 다시 읽어오는 과정에서 힙 메모리 초과 에러가 났습니다.
+ 데이터 분석쪽이랑 상의했고, 파일 10개로 나눠서 데이터를 수집하기로 했습니다.

## 💡 주의 사항
+ 데이터가 수집될 때 중복으로 들어오고 있는 것 같아서, 이 부분은 찬우님이 다시 확인해주신다고 합니당
+ 만약 중복이 해결되면 하루에 수집되는 데이터가 좀 줄어들텐데, 굳이 10개로 나눠놓았으니 bulk insert 한 효과가 없을 것 같기도 하네요.

그래서 생각해본 방법이..

1.  힙이 감당할 정도의 사이즈 이상을 넘어가면 파일을 10개로 나누고, 아니면 한 파일로 수집한다. (하지만 그 기준 정하기가 애매) 
2. 아예 10개로 나누어 놓지 않으면 이후 DB 데이터가 날라가고 새롭게 가져올 때 또 힙 메모리 초과가 발생한다.

어떻게 생각하시나요. 좋은 대안이 있을까요?🤔

2023-10-29 02:13 UTC, mangchhe commented
@semi-cloud 
로직 간단하게 설명 가능하세요?
파일을 열개로 나눠서 한다는게 무슨말인지 모르겠네요.

2023-10-29 15:01 UTC, semi-cloud commented
@mangchhe 
> 파일을 10개로 나눠서 한다는게 무슨말인지 모르겠네요.

1. 기존 방식
+ 데이터 팀에서 `all.json` 파일 하나로 크롤링 데이터를 수집 + 스프링 부트에서 파일 전체를 한번에 읽어오다 보니 힙 메모리 초과 예외 발생

2. 바뀐 방식
+ 파일 전체를 한번에 읽어오지 않도록, 데이터 팀에서 애초에 크롤링 데이터를 10개 파일로 나눠서 수집하도록 변경했습니다. (한 파일을 BufferedReader로 나눠서 읽어오기에는 List<Map<String, DTO>> 형태여서 불가능한 상황이였습니다)
+ 현재 batch size 를 100으로 해놓았기 때문에, 1000개 이상 데이터면 한번에 100개씩 10번 넣는거나 파일 10개로 나누는거나 똑같다고 판단하여, 1000개 이하면 파일 하나로 이상이면 파일 10개로 나누도록 생각해봤는데 어떨까요? 👀

이해 안가시면 다시 말씀해주세용.

2023-10-30 06:46 UTC, mangchhe commented
@semi-cloud 
- `BufferedReader`로도 가능할 거 같긴한데 안되던가요?
- `all.json` 크기가 어떻게 되나요? 단순히 텍스트라서 초과할 정도의 양은 아닐 거 같은데 당일 크롤링 건 말고 이전 크롤링 데이터들도 모두 가지고 있는건가요?

2023-10-31 02:15 UTC, semi-cloud commented
@mangchhe 
1. `BufferedReader`로 일정 부분만 가져와서 `ObjectMapper`가 `DTO` 객체로 변환하려면, `Json` 파일이 대충 아래와 같은 구조여야 했는데 해당 형식이 불가능했습니다. 무조건 파일 시작과 끝을 감싸는 `[ ]` 가 있어야하더라구요. 뭐 더 방법이 있었을 수도 있겠지만, 너무 복잡해져서 파일을 쪼개는 방식으로 선택했습니다. 

```
 "key" : {
 
 },
 "key" : {
 
 }
```
혹시 좋은 방법 생각나실까용?

2. 네 이전 모든 크롤링 데이터를 가지고 있었습니다. 크기는 173MB 입니당.

2023-10-31 02:45 UTC, mangchhe requested changes
> BufferedReader로 일정 부분만 가져와서 ObjectMapper가 DTO 객체로 변환하려면, Json 파일이 대충 아래와 같은 구조여야 했는데 해당 형식이 불가능했습니다. 무조건 파일 시작과 끝을 감싸는 [ ] 가 있어야하더라구요. 뭐 더 방법이 있었을 수도 있겠지만, 너무 복잡해져서 파일을 쪼개는 방식으로 선택했습니다.

굳이 DTO로 변환을 해야할까요. 행 단위로 짤라서 처리 가능해보이네요.

> 네 이전 모든 크롤링 데이터를 가지고 있었습니다. 크기는 173MB 입니당

이건 데이터 팀에서 효율적으로 데이터를 관리해야 할 것 같아요. 

매일 한 번씩 크롤링하는 걸로 아는데 일자 단위로 파일을 나눠서 데이터를 담는다든가 하면 좋을 것 같네요.

지금 힙 메모리 부족을 떠나서 크롤링 된 데이터가 비효율적으로 관리되고 있는 거 같네요.

2023-10-31 07:58 UTC, semi-cloud commented
@mangchhe 
> 굳이 DTO로 변환을 해야할까요. 행 단위로 짤라서 처리 가능해보이네요.

+ 행 단위로 자른다는게 어떤 말씀이실까요?! `BufferedReader` 에서 몇번째 행부터 몇번째 행까지만 가져오라 지정하는게 가능했던가..? 

>이건 데이터 팀에서 효율적으로 데이터를 관리해야 할 것 같아요.
매일 한 번씩 크롤링하는 걸로 아는데 일 단위로 파일을 나눠서 데이터를 담는다든가 하면 좋을 것 같네요.
지금 힙 메모리 부족을 떠나서 크롤링 된 데이터가 비효율적으로 관리되고 있는 거 같네요.

+ 아하 현재 아래와 같은 방식으로 관리되고 있었습니다. 주현님 말씀대로 일별로 관리하면 서버 메모리를 너무 잡아먹을 것 같아서 새롭게 비우고 덮어 씌우는 방식을 선택하고, 혹시나 데이터가 모두 날라가는 상황을 대비해서 모든 데이터를 가져올 수 있도록 하는 옵션이 있었습니다.
1.  `-ca` 옵션 -> all.json 파일에 모든 데이터가 수집됌
2. `-ua` 옵션 -> all.json 파일에 하루 마다의 크롤링 데이터가 덮어 씌워짐

문제가 발생했던 상황은 DB 데이터가 모두 날라간 상황이라 -ca 옵션으로 모든 데이터가 필요했구요!

2023-10-31 09:03 UTC, mangchhe commented
@semi-cloud 

json 파일 원본을 여기다가 올려주실래요?

2023-10-31 11:16 UTC, semi-cloud commented
@mangchhe 
> json 파일 원본을 여기다가 올려주실래요? 제가 말한 건 `{}`로 시작과 끝을 알 수 있으니 처리할 수 있지 않냐는 말이었습니다.

헉 이미 데이터 팀에서 10개 나눈 상태로 리팩토링이 완료되어서, 지금 `all.json` 원본은 없네요. 지금 임시로 만든 데이터 2개짜리 파일이라두,, JSON 형식 보시려구 하는거 맞죠?

[test.json](https://github.com/ahachulTeam/ahachul_backend/files/13215584/test.json)

2023-11-02 18:27 UTC, mangchhe reviewed
1. 
제가 했던 말은 이런 식으로 구현해서 처리해도 되지 않겠냐는 말이었습니다.
```kotlin
@Test
fun jsonParsingTest() {
    val gson = Gson()

    val jsonFilePath = "test.json"
    val reader = BufferedReader(FileReader(jsonFilePath))
    
    var jsonStr = ""
    var isRecord = false
    var line: String?
    
    while (reader.readLine().also { line = it } != null) {
        if (line!!.trim().startsWith("\"V")) {
            jsonStr = "{"
            isRecord = true
            continue
        }

        if (!isRecord) continue

        jsonStr += line

        if (line!!.trim().startsWith("}")) {
            val item = gson.fromJson(jsonStr, Item::class.java)

            // 필요한 로직
            isRecord = false
        }
    }

    reader.close()
}

data class Item(
    val title: String,
    val getDate: String,
    val getPlace: String,
    val type: String,
    val receiptPlace: String,
    val storagePlace: String,
    val lostStatus: String,
    val phone: String,
    val context: String,
    val image: String,
    val source: String,
    val page: String
)
```
2. 
고정 열 개로 하는 것보다는 일자 단위는 너무 많을 테니 개월 수(3개월, 6개월 단위 등)로 잘라도 괜찮을 것 같네요.

2023-11-05 02:17 UTC, semi-cloud commented
@mangchhe 
> 제가 했던 말은 이런 식으로 구현해서 처리해도 되지 않겠냐는 말이었습니다.

와우 이런 방법이 있었군요 굳굳 👏

> 고정 열 개로 하는 것보다는 일자 단위는 너무 많을 테니 개월 수(3개월, 6개월 단위 등)로 잘라도 괜찮을 것 같네요.

혹시 왜 열개로 고정해서 나누는 방식이 좋지 않은지 여쭤봐도 될까요!?
그리고 주현님이 올려주신 방식대로 100개씩 데이터를 처리한다면 그냥 파일 하나로 뭉쳐도 괜찮을 것 같기두 하네요..! (일별로, 개월 별로 나누지 않고)

2023-11-05 06:46 UTC, mangchhe commented
> 혹시 왜 열개로 고정해서 나누는 방식이 좋지 않은지 여쭤봐도 될까요!?
좋지 않다기 보단

2023-11-05 06:52 UTC, mangchhe commented
@semi-cloud 

> 혹시 왜 열개로 고정해서 나누는 방식이 좋지 않은지 여쭤봐도 될까요!?

좋지 않다기보단 지금 파일 열 개로 나누셨는데 기준이 없어요. 5개도 되고 20개도 되는데 왜 10개로 하신 거에요에 대해 대답 어떻게 하실껀가요?

그리고 저 파일 또한 먼 훗날 용량이 커지게 되면 열 개로도 불가능하게 될 수도 있고 파일이 누락되거나(훼손) 됐을 때 구체적으로 어떤 파일인지 명시되어 있으면 좋겠죠.? 기타 등등 이유가 있을 것 같아요.

2023-11-15 10:51 UTC, semi-cloud commented
@mangchhe 
해당 풀리퀘 닫고 수정 사항 반영해서 따로 올릴게요~!

2023-11-15 10:51 UTC, closed without merging