✨ 애플 로그인 기능 추가 (#228)
ahachulTeam/ahachul_backend2 pull request #233
Opened 2024-10-28 04:21 UTC by discphy

## 📚 개요
+ #228 

## ✏️ 작업 내용
- [X] 애플 로그인 기능 구현

## 💡 주의 사항
+ 애플 키 파일 `.p8` 파일을 [ahachul_secret](https://github.com/ahachulTeam/ahachul_secret) repo에서 관리해도 될까요?
+ `OAuthProperties`에 애플에서 사용하는 설정정보들을 사용하기 위하여 `Properties`를 추가하였습니다.  
+ 애플에서 제공하는 사용자 정보에 `id`, `email` 뿐이라서 `isNeedAdditionalUserInfo`값이 항상 `true` 입니다.

2024-11-02 10:25 UTC, semi-cloud requested changes
수고하셨습니다 👍 conflict랑 자잘한 것만 수정해주시면 될 것 같아요.

2024-11-02 10:25 UTC, semi-cloud commented on ahachul_backend/src/main/kotlin/backend/team/ahachul_backend/common/client/impl/AppleMemberClientImpl.kt
> +        val tokenParts: List<String> = idToken.split(".")
혹시 여기서 사용자 정보를 IdToken으로 가져오는거랑, 액세스 토큰으로 가져오는거랑 차이가 있나요? 
애플에서 값을 같이 주길래 그냥 궁금해서 여쭤봤습니당

2024-11-02 10:25 UTC, semi-cloud commented on ahachul_backend/src/main/kotlin/backend/team/ahachul_backend/common/client/impl/AppleMemberClientImpl.kt
> +    override fun getIdTokenByCode(code: String): String {
IdToken verify 과정은 클라이언트가 아니고 서버에서 받아온거라 필요 없는게 맞을까요? 애플 로그인 넘 헷갈리네요 🙃
https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user#3383769

2024-11-02 10:25 UTC, semi-cloud commented on ahachul_backend/src/main/kotlin/backend/team/ahachul_backend/common/properties/OAuthProperties.kt
> +        val accessType: String?,
실수로 `,` 가 들어간 것 같네요

2024-11-03 04:43 UTC, discphy commented on ahachul_backend/src/main/kotlin/backend/team/ahachul_backend/common/client/impl/AppleMemberClientImpl.kt
> +        val tokenParts: List<String> = idToken.split(".")
@semi-cloud 차이가 있는지는 모르겠는데.. ㅎㅎ 찾아보니깐(?) `access_token`으로 구체적인 사용자 정보(`id_token`으로는 사용자 고유 ID, 이메일정도만 가져올 수 있음)를 가져올 수 있는 것 같습니다. 하지만 `access_token`을 사용하기 위해선 리다이렉트를 form post로 전달을 받아야하기 때문에 프론트에서 직접 못받아 프로세스가 다소 복잡해질 우려가 있어 `id_token`으로 구현했습니다. 😂

2024-11-03 07:32 UTC, discphy commented on ahachul_backend/src/main/kotlin/backend/team/ahachul_backend/common/client/impl/AppleMemberClientImpl.kt
> +    override fun getIdTokenByCode(code: String): String {
@semi-cloud 이부분은 고려 못해봤는데... `IdToken`의 유효성 검증을 해야될지 고민좀 해봐야겠네요.. 이슈로 남길지 의문입니다 😂

2024-11-03 14:39 UTC, semi-cloud commented on ahachul_backend/src/main/kotlin/backend/team/ahachul_backend/common/client/impl/AppleMemberClientImpl.kt
> +    override fun getIdTokenByCode(code: String): String {
아하 넵 우선 백로그로 남겨두시죠!

2024-11-03 14:41 UTC, semi-cloud approved these changes
🙃

2024-11-03 23:19 UTC, discphy commented on ahachul_backend/src/main/kotlin/backend/team/ahachul_backend/common/client/impl/AppleMemberClientImpl.kt
> +    override fun getIdTokenByCode(code: String): String {
이슈에 올렸습니다! 👍

https://github.com/ahachulTeam/ahachul_backend/issues/234

2024-11-04 03:28 UTC, hwgyun approved these changes

2024-11-04 03:39 UTC, merged